export const services = [
  {
    slug: "remote-it-support",
    title: "Remote IT Support",
    eyebrow: "Fast, practical help",
    summary: "Resolve everyday computer, software, email, and access issues without waiting for an on-site visit.",
    description: "When technology interrupts the workday, we connect securely, explain what is happening in plain language, and get your team moving again. We also document recurring issues so the same problem is less likely to return.",
    image: "/images/remote-it-support.webp",
    included: ["Secure remote troubleshooting", "Email and application support", "Login and access recovery", "Printer and peripheral help", "Software updates and cleanup", "Issue notes and next-step guidance"],
    outcomes: ["Less downtime for employees", "A clear point of contact for IT questions", "Fewer repeated problems", "Support that scales with your team"],
    process: [
      { title: "Tell us what changed", text: "Share the issue, affected device, and any message you see." },
      { title: "We connect securely", text: "With your permission, a technician reviews the problem remotely." },
      { title: "Fix, test, explain", text: "We confirm the solution with you and leave clear notes for next time." },
    ],
    idealFor: ["Teams without internal IT staff", "Remote and hybrid employees", "Owners who need one dependable support contact"],
    faq: [
      { question: "What can be fixed remotely?", answer: "Most software, email, account, update, performance, printer, and configuration issues can be resolved remotely. If hands-on work is required, we explain the safest next step." },
      { question: "Can you support both Windows and Mac?", answer: "Yes. We support common Windows and macOS business environments and the applications small teams use every day." },
    ],
  },
  {
    slug: "device-management",
    title: "Device Management",
    eyebrow: "Organized devices, safer work",
    summary: "Set up, track, maintain, and retire business laptops and mobile devices with a repeatable process.",
    description: "Every device that reaches company files should be configured consistently. We create a practical device standard, apply essential security settings, manage updates, and keep an understandable inventory as employees join or leave.",
    image: "/images/device-management.webp",
    included: ["New laptop and mobile setup", "Device inventory and ownership records", "Update and patch coordination", "Encryption and screen-lock settings", "Employee onboarding and offboarding", "Secure device retirement guidance"],
    outcomes: ["Consistent setup across the team", "Better control of company access", "Faster employee onboarding", "Reduced risk from lost or old devices"],
    process: [
      { title: "Inventory", text: "We record the devices, owners, operating systems, and business purpose." },
      { title: "Standardize", text: "We agree on practical settings, applications, access, and update rules." },
      { title: "Maintain", text: "Devices are reviewed, updated, and adjusted as your team changes." },
    ],
    idealFor: ["Growing teams adding laptops regularly", "Hybrid businesses", "Companies handling client or financial information"],
    faq: [
      { question: "Do we need special management software?", answer: "Not always. We recommend tools only when they reduce work or risk for your actual number of devices and working style." },
      { question: "Can you prepare a laptop for a new employee?", answer: "Yes. We can configure accounts, security settings, email, approved applications, and access before the employee starts." },
    ],
  },
  {
    slug: "microsoft-365-setup",
    title: "Microsoft 365 Setup",
    eyebrow: "Work together with less friction",
    summary: "Configure Microsoft 365 email, files, calendars, and security around the way your team actually works.",
    description: "A thoughtful Microsoft 365 setup makes communication simpler and protects business information. We organize users, shared mailboxes, Teams, OneDrive, SharePoint, permissions, and essential security without overcomplicating the environment.",
    image: "/images/microsoft-365-setup.webp",
    included: ["Tenant and domain configuration", "User, alias, and shared mailbox setup", "Teams and shared file structure", "OneDrive and SharePoint permissions", "Multi-factor authentication", "Migration planning and staff guidance"],
    outcomes: ["Professional company email", "Clear access to shared information", "Safer sign-ins", "A setup employees can understand"],
    process: [
      { title: "Plan the workspace", text: "We map users, email addresses, shared files, and collaboration needs." },
      { title: "Configure and migrate", text: "Accounts, security, mail, calendars, and files are prepared carefully." },
      { title: "Launch with guidance", text: "We test access and show employees the daily actions they need." },
    ],
    idealFor: ["Businesses moving from personal email", "Teams replacing an inconsistent setup", "Companies adding Microsoft Teams or SharePoint"],
    faq: [
      { question: "Can you migrate our existing email?", answer: "Yes. We first review the current provider, mailbox sizes, aliases, calendars, and timing, then create a migration plan designed to limit disruption." },
      { question: "Will employees need training?", answer: "We provide short, role-relevant guidance so people know how to sign in, find shared files, use email safely, and ask for help." },
    ],
  },
  {
    slug: "google-workspace-setup",
    title: "Google Workspace Setup",
    eyebrow: "Simple cloud collaboration",
    summary: "Build a clean Google Workspace environment for business email, shared files, calendars, and meetings.",
    description: "We configure Google Workspace so staff can find what they need without exposing information too broadly. That includes business email, groups, shared drives, calendars, account security, and practical administrative controls.",
    image: "/images/google-workspace-setup.webp",
    included: ["Domain and Workspace configuration", "Business Gmail accounts and groups", "Shared drives and access structure", "Calendar and meeting setup", "Two-step verification", "Data migration and user guidance"],
    outcomes: ["Consistent business communication", "Organized team file sharing", "Safer account access", "Simple administration as the team grows"],
    process: [
      { title: "Review", text: "We learn how your team communicates, stores files, and shares calendars." },
      { title: "Build", text: "The domain, users, groups, drives, policies, and security are configured." },
      { title: "Move and verify", text: "Data is migrated where needed, then access and mail flow are tested." },
    ],
    idealFor: ["Teams that prefer Gmail and Google Drive", "Startups formalizing business accounts", "Businesses consolidating scattered Google files"],
    faq: [
      { question: "Can personal Gmail data be moved?", answer: "In many cases, mail, calendars, contacts, and Drive files can be transferred or reorganized. We assess ownership and sharing before the move." },
      { question: "Can we limit who sees shared files?", answer: "Yes. We design groups and shared-drive access around roles, then review external-sharing settings with you." },
    ],
  },
  {
    slug: "business-email-setup",
    title: "Business Email Setup",
    eyebrow: "Professional, dependable email",
    summary: "Create business email on your own domain with sensible security, shared addresses, and reliable delivery.",
    description: "We help you choose the right platform, connect the domain correctly, create staff and shared addresses, and protect accounts. The result is business email that looks professional and is easier to manage.",
    image: "/images/business-email-setup.webp",
    included: ["Domain and mailbox configuration", "User aliases and shared addresses", "Email authentication records", "Spam and phishing protection", "Mobile and desktop setup", "Mailbox migration planning"],
    outcomes: ["Email from your company domain", "Better message delivery", "Reduced account takeover risk", "Clear ownership of shared inboxes"],
    process: [
      { title: "Choose the platform", text: "We compare the practical fit of Microsoft 365, Google Workspace, or your current provider." },
      { title: "Configure the domain", text: "Mail records and authentication are set carefully to support delivery and trust." },
      { title: "Connect the team", text: "Mailboxes are added to approved devices and tested end to end." },
    ],
    idealFor: ["New businesses using a company domain", "Teams moving away from shared passwords", "Companies experiencing delivery or spam issues"],
    faq: [
      { question: "Will we lose old email?", answer: "A planned migration usually preserves existing mail. We confirm what can be moved and how long the transition should take before making changes." },
      { question: "Can you create addresses like billing@ or support@?", answer: "Yes. We can create shared mailboxes, groups, or aliases and define who should receive and respond to them." },
    ],
  },
  {
    slug: "cloud-backup",
    title: "Cloud Backup",
    eyebrow: "Recover what matters",
    summary: "Protect essential files, cloud accounts, and business records with backups that are checked—not merely assumed.",
    description: "Syncing is useful, but it is not always a complete backup. We identify critical information, choose sensible retention, automate protected copies, and test recovery so your plan works when a file is deleted or a device fails.",
    image: "/images/cloud-backup.webp",
    included: ["Backup needs assessment", "Workstation and file backup", "Microsoft 365 or Google Workspace backup", "Retention and version planning", "Backup monitoring", "Recovery testing and documentation"],
    outcomes: ["Recoverable business files", "Protection from accidental deletion", "Less reliance on a single device or account", "A documented recovery path"],
    process: [
      { title: "Identify critical data", text: "We map where important files, mail, and records live today." },
      { title: "Protect", text: "Automated encrypted backups are configured with appropriate retention." },
      { title: "Prove recovery", text: "We test representative restores and document who to contact and what to expect." },
    ],
    idealFor: ["Businesses relying on cloud files", "Teams storing records on individual laptops", "Companies without a tested recovery plan"],
    faq: [
      { question: "Is OneDrive or Google Drive already a backup?", answer: "They provide useful versioning and recycle bins, but separate backup can add longer retention, independent recovery, and protection from account-wide incidents." },
      { question: "How often should recovery be tested?", answer: "The right schedule depends on how often data changes and how costly downtime would be. We recommend a practical cadence and record the results." },
    ],
  },
  {
    slug: "network-wifi-support",
    title: "Network & Wi-Fi Support",
    eyebrow: "A steadier connection",
    summary: "Improve office Wi-Fi coverage, reliability, guest access, and basic network security without unnecessary complexity.",
    description: "Slow or unstable connectivity affects every cloud tool your business uses. We review the office layout and equipment, separate business and guest access, improve coverage, and document the network for easier future support.",
    image: "/images/network-wifi-support.webp",
    included: ["Connectivity and coverage review", "Router and access-point configuration", "Business and guest Wi-Fi separation", "Secure password and firmware practices", "Printer and device connectivity", "Network documentation"],
    outcomes: ["More reliable daily connectivity", "Better coverage in work areas", "Safer guest access", "Faster troubleshooting when issues occur"],
    process: [
      { title: "Assess", text: "We review symptoms, layout, internet service, equipment, and connected devices." },
      { title: "Improve", text: "Configuration, placement, security, and equipment are adjusted where they add value." },
      { title: "Document", text: "We record the setup and confirm staff and guest connections work as intended." },
    ],
    idealFor: ["Small offices with dead zones", "Teams experiencing dropped calls", "Businesses sharing one Wi-Fi password with visitors"],
    faq: [
      { question: "Do we need a faster internet plan?", answer: "Sometimes, but not always. Coverage, interference, aging equipment, or configuration may be the actual cause. We assess before recommending a change." },
      { question: "Can you help with a new office?", answer: "Yes. We can plan equipment locations, business and guest networks, secure configuration, and a documented handover." },
    ],
  },
  {
    slug: "cybersecurity-basics",
    title: "Cybersecurity Basics",
    eyebrow: "Practical protection, clearly explained",
    summary: "Reduce common small-business risks with safer sign-ins, updates, devices, email, and employee habits.",
    description: "Cybersecurity does not need to begin with a complex enterprise project. We prioritize the controls that matter most for a small team, explain why they help, and create a realistic improvement plan.",
    image: "/images/cybersecurity-basics.webp",
    included: ["Multi-factor authentication", "Account and administrator review", "Device encryption and updates", "Email and phishing protection", "Password manager rollout", "Basic incident-response checklist"],
    outcomes: ["Stronger protection against stolen passwords", "Reduced exposure from old accounts", "Safer employee devices", "A clear response plan for suspicious activity"],
    process: [
      { title: "Baseline", text: "We review accounts, devices, email, backups, and current security habits." },
      { title: "Prioritize", text: "Risks are ranked by likely impact and effort so improvements stay manageable." },
      { title: "Strengthen", text: "We implement agreed safeguards and give the team simple usage guidance." },
    ],
    idealFor: ["Businesses handling customer information", "Teams concerned about phishing", "Owners unsure which security improvements matter first"],
    faq: [
      { question: "Can you guarantee we will never be hacked?", answer: "No provider can make that guarantee. We reduce common risks, improve detection and recovery, and help your team respond more confidently." },
      { question: "Will security slow employees down?", answer: "Good controls should be proportionate. We favor settings and tools that provide meaningful protection without creating unnecessary daily friction." },
    ],
  },
  {
    slug: "it-support-plans",
    title: "IT Support Plans",
    eyebrow: "Ongoing help that fits the team",
    summary: "Combine day-to-day support, maintenance, advice, and planned improvements in one predictable service.",
    description: "An ongoing support plan gives owners and employees a clear place to ask for help. We agree on devices, users, priorities, included services, and review points so IT becomes a managed business function rather than a string of emergencies.",
    image: "/images/it-support-plans.webp",
    included: ["Remote help desk", "Routine device and account maintenance", "New employee setup", "Backup and security checks", "Technology planning", "Regular service review"],
    outcomes: ["Predictable access to support", "Fewer neglected maintenance tasks", "Consistent onboarding and offboarding", "Better planning for technology costs"],
    process: [
      { title: "Discovery", text: "We review the team, devices, services, recurring issues, and business priorities." },
      { title: "Support plan", text: "Scope, service expectations, communication, and priorities are documented clearly." },
      { title: "Operate and review", text: "We handle support and maintenance, then revisit needs as the business changes." },
    ],
    idealFor: ["Businesses with 3–50 employees", "Owners spending too much time on IT", "Teams needing regular support without a full-time hire"],
    faq: [
      { question: "Are plans one-size-fits-all?", answer: "No. We use a consistent service framework but shape coverage around your users, devices, systems, working hours, and priorities." },
      { question: "Can we start with a one-time project?", answer: "Yes. Many clients begin with an email, device, backup, or security project before choosing ongoing support." },
    ],
  },
  {
    slug: "request-technical-support",
    title: "Request Technical Support",
    eyebrow: "Start with the issue in front of you",
    summary: "Tell us what is happening, who is affected, and how urgent it feels. We will reply by email with the next step.",
    description: "You do not need to diagnose the problem before contacting us. Describe what you were trying to do, what changed, and any message you can see. We will use that information to route the request and explain the next practical step.",
    image: "/images/request-technical-support.webp",
    included: ["Clear email acknowledgment", "Initial issue review", "Remote support scheduling", "Plain-language next steps", "Escalation guidance when hands-on service is required", "Options for ongoing support"],
    outcomes: ["A clear starting point", "Less time guessing at the cause", "Support matched to the issue", "Useful follow-up documentation"],
    process: [
      { title: "Send the request", text: "Share the affected person, device, symptom, and business impact." },
      { title: "We review", text: "A coordinator assesses the details and identifies the right support path." },
      { title: "Take the next step", text: "You receive an email with questions, scheduling details, or immediate guidance." },
    ],
    idealFor: ["New clients with a current issue", "Owners who are unsure which service fits", "Teams that need remote help"],
    faq: [
      { question: "What should I include in the request?", answer: "Include the affected person, device, what you were doing, when the issue began, any visible error, and whether work is fully blocked." },
      { question: "Should I send passwords?", answer: "No. Never include passwords, verification codes, or other sensitive credentials in the form or email." },
    ],
  },
];
